### ISSUE TITLE
Problem with PHP cURL

### ISSUE THREAD

**Issue by pjdevries** [degobbis/docker-lamp#11]
I am having problems with a PHP cURL connection. When trying to access a URL from within a custom component to another part of the same site, I get a 400 `Failed to connect to foo.bar.local port 8480 after 1 ms: Connection refused`. Accessing that same URL from Postman succeeds.

Any idea what may cause this? Could this be something in the Docker setup?

**Comment by degobbis** [comment]
Try to test this:
1. Shut down the docker lamp.
2. On Your host, get the docker network adaptor ip by calling ` ip a | grep -i 'docker'` like `inet 172.17.0.1/16`.
3. Change the IPs on `TLD_SUFFIX`, `EXTRA_HOSTS` if used and `REMOTE_HOST_IP` to this IP.
4. Start the docker lamp again.

I hope this fix the Problem.

**Comment by pjdevries** [comment]
It seems to solve the problem indeed. Thanx.
