### ISSUE TITLE
Xdebug profiling; volume for xdebug.output_dir

### ISSUE THREAD

**Issue by pjdevries** [degobbis/docker-lamp#12]
Hi Guido,

I want to enable Xdebug profiling. If I understand the docker-lamp setup correctly, I can place a `php.ini` override in a user `.../data/php/phpNN` directory, containing any needed Xdebug settings. But how/where do I add a volume to mount the `xdebug.output_dir` for easy accessibility and analysis?

**Comment by degobbis** [comment]
Hi,
APP_BASEDIR is mapped inside the PHP container to /srv.

So each directory you create in APP_BASEDIR will be callable as path starting with /srv/PATH




10.10.2022 19:49:20 Pieter-Jan de Vries ***@***.***>:

**Comment by pjdevries** [comment]
Thank you again for the swift response. I could have and should have realized this myself. Apologies for bothering you.

**Comment by degobbis** [comment]
You are welcome

10.10.2022 21:27:33 Pieter-Jan de Vries ***@***.***>:

**Comment by degobbis** [comment]
Is this issue solved for you?

**Comment by pjdevries** [comment]
Yes it us. Thank you.
