### ISSUE TITLE
Command docker-compose or docker compose | without or with hyphen

### ISSUE THREAD

**Issue by astridx** [degobbis/docker-lamp#14]
In a new installation docker-lamp does not start, because the hyphen between docker and compose is no longer used:

See for example: https://www.heise.de/ratgeber/FAQ-Container-mit-Docker-und-die-Feinheiten-von-Docker-Compose-7138016.html

**Comment by degobbis** [comment]
@astridx THX to bring my attention to this.

**Comment by astridx** [comment]
This place too?

https://github.com/degobbis/docker-lamp/blob/72b598e8e397ef7482d5e70eec4ad8f44e02da3a/.config/functions.sh#L423
