### ISSUE TITLE
How to activate getimagesize

### ISSUE THREAD

**Issue by astridx** [degobbis/docker-lamp#15]
I like to use this function: https://www.php.net/manual/de/function.getimagesize.php

In the container docker-lamp_apache24 the function is not available under php 8.1. 

Can you support me in configuring this?

**Comment by degobbis** [comment]
Are You using the latest image version (8.1.12)?
To be sure to use the latest versions, use this commands:
1. `./docker-lamp shutdown`
2. `./docker-lamp update-images`
3. `./docker-lamp delete-obsolete-images`
4. `./docker-lamp start`

**Comment by astridx** [comment]
Thank you for the answer. Yes, the docker-lamp environment is all up to date. The getimagesize function needs something, which is probably to be set. It works under XAMPP without docker. I will have a closer look next week. I was hoping you would know right off the bat.

--

Vielen Dank für die Antwort. Ja, die docker-lamp Umgebung ist auf dem neuesten Stand. Die Funktion getimagesize benötigt etwas, was wohl in der php.ini oder auf dem Server einzustellen ist. Unter XAMPP lokal funktioniert es. Ich werde mir das nächste Woche mal genauer ansehen. Ich hatte gehofft, dass Du es auf Anhieb weißt.

**Comment by degobbis** [comment]
I tested it with all php versions, I get no error back. All works fine.

**Comment by astridx** [comment]
Thank you.

I always get an image size of 0.0 at this point. 
https://github.com/astridx/pkg_agadvents/blob/master/j4/pkg_agadvents/src/modules/mod_agadvent/tmpl/default.php#L20

The debugger just goes over it. i can't get into the function.

I never had this problem before. Others reported it to me. Mostly it was because allow_url_fopen was disabled. 

But I'll have another look next week.
