### ISSUE TITLE
getopt: illegal option -- o

### ISSUE THREAD

**Issue by loadbrain** [degobbis/docker-lamp#16]
On my MacBook, M2, Ventura 13.0.1 I get following error when calling `docker-lamp start`
`getopt: illegal option -- o
ERROR: The parameter is not set correctly!`

Any ideas?

**Comment by degobbis** [comment]
Habe You installed `gnu-getopt` as described in the requirements?

**Comment by loadbrain** [comment]
Yes, exactly that way. I use zsh, but that should not be the problem I think...

**Comment by degobbis** [comment]
Is there a way to get in contact with You for a chat or a meetup? 
I'm not using MacOS, so we need to debug it live.

**Comment by loadbrain** [comment]
Yes,of course.Not today but maybe Tuesday, is this ok for you?In the afternoon or evening?Public Key: http://keys.openpgp.org/Am 20.11.2022 um 14:37 schrieb Guido De Gobbis ***@***.***>:﻿
Is there a way to get in contact with You for a chat or a meetup?
I'm not using MacOS, so we need to debug it live.

**Comment by degobbis** [comment]
Get in contact with me over mattermost 
http://joom.la/chat - @guido-de-gobbis
so we can find a day/time

**Comment by loadbrain** [comment]
Ok. I will try it too on manjaro Linux, to check if it works for me there.

**Comment by loadbrain** [comment]
Just for info, installed on my Ubuntu machine, no problems

**Comment by loadbrain** [comment]
Possible reason:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by degobbis** [comment]
My images are only created for amd64 architecture.

**Comment by loadbrain** [comment]
So, I will try to fork and check if I can get it working with arm64v8.
Good training for me…

**Comment by degobbis** [comment]
My images are created here
https://github.com/degobbis/docker-builds
