### ISSUE TITLE
Issues after moving from WSL2 to Kubuntu

### ISSUE THREAD

**Issue by pjdevries** [degobbis/docker-lamp#17]
Hi Guido,

I just moved from a Windows WSL2 environment to Kubuntu, expecting my docker environment to run without problems, after simply moving everything across. Unfortunately that's not the case. Because I was working with a slightly customized branch from your `2.0.0-dev`, I started from scratch with the original. These are the two issues I ran into thus far:

- No matter what I try, I can not access docker sites from my Kubuntu host. I only can after adding them specifically to `/etc/hosts`.
- The MySQL container won't run. Neither 5.7 nor 8.0.

Any ideas how to debug and solve those issues?

**Comment by degobbis** [comment]
Hello Pieter-Jan,

please first make sure that port 53 is free in Kubuntu and that the BIND container is started when docker-lamp boots.

If that fits, go into the network settings of your connection and set it to get only the IP dynamically.

Then set the domain server to 127.0.0.1,<ROUTER IP> and restart the network connection.

This is necessary so that DNS queries are first run on the BIND container and then resolved externally.

Then the domains should be resolved again.

About MySQL, actually the same, make sure port 3306 is not used before you start.

**Comment by pjdevries** [comment]
I found the culprit of that second issue: `db-data-dir`. This location does not change when switching databases. If a MariaDB database already exists, which happened in my case, switching to MySQL fails. 

In the custom branch I used in WSL2 I already made a provision for keeping my databases in directories of my choosing, being my custom `.../data/db/DATABASE_TO_USE` . This automatically prevents this conflict from occurring.

Once I have everything working properly again, I will send a pull request for that modification.

**Comment by degobbis** [comment]
In my version the db-data directory is only used as a volume. If you want to switch between MariaDB and MySQL, then you have to shutdown the server with shutdown and start it up again after the change in the.env.

The databases are stored in the initDB folder and reloaded on startup.

So there are no problems with the switch.

**Comment by pjdevries** [comment]
> In my version the db-data directory is only used as a volume. If you want to switch between MariaDB and MySQL, then you have to shutdown the server with shutdown and start it up again after the change in the.env.
> 
> The databases are stored in the initDB folder and reloaded on startup.
> 
> So there are no problems with the switch.

I guess you assume `ARCHIVE_DATABASES=1`, which it is not in my case and actually does cause the mentioned problem :)

**Comment by degobbis** [comment]
Nope,
This option, I mean, is currently without functionality.

On shutdown the server, my script will save all the databases as SQL dumps and the db-data-dir volume will be deleted.
At startup, the databases are restored in the new database system. This avoids exactly this error.

**Comment by pjdevries** [comment]
What can I say. The only thing I can say is the problem occurred before I moved the databases out of the `db-data-dir` volume and disappeared once I moved them to a custom location. 

Apart from solving my problem, my adjustment allows moving the databases to a custom location. Is it a PR worth looking at or do I not need to bother?

**Comment by degobbis** [comment]
Thanks for your suggestion, but it's not necessary.
The db-data-dir volume is only temporary and will be deleted on clean shutdown and created again on startup.

The databases are in the APP_BASEDIR/initDB folder and are restored on startup.

Another approach does not make sense to me, because otherwise you would have to duplicate the databases for the different database types, or the volumes must never break (otherwise data loss).

It also has the advantage that I can also feed the database dumps to an online server at any time.

Can we close the issue then?

**Comment by pjdevries** [comment]
It's your repo, so you can close it whenever you like :D However, having the ability to move database to a custom location, does not mean one has to. One of the things I appreciate about your setup, is it configurability. This also is just a configurable option.

Before closing the topic, I do still have some difficulty getting BIND to do it's thing. Port 53 is free, the BIND container is running and `resolvectl status` says `DNS Servers: 127.0.0.1`. Unfortunately my domains are still not reachable without an `/etc/host` entry. Any more suggestions?

**Comment by degobbis** [comment]
what says for example `nslookup joomla.local`

**Comment by degobbis** [comment]
Postscript:
Did you check the IP for the mapping in the .env?

**Comment by degobbis** [comment]
Can you please post the output of `/etc/resolv.conf`?
Also the values from `REMOTE_HOST_IP`, `TLD_SUFFIX` and `BIND_DNS_RESOLVER`

**Comment by pjdevries** [comment]
> what says for example nslookup joomla.local

That's a clever one. It says:

```
Server:         192.168.10.9
Address:        192.168.10.9#53

** server can't find joomla.local: NXDOMAI
```

My workstation gets it's ip address and other stuff from a FRITZ!Box DHCP server, which also serves as the gateway and forwarding DNS server. It appears requests are sent to the FRITZ!Box, even though  `resolvectl status` reports `127.0.0,1` being the DNS.

> Can you please post the output of /etc/resolv.conf?

```
ameserver 192.168.10.9
nameserver 127.0.0.1
nameserver fd00::e228:6dff:fe7c:a466
search .
```

Bare in mind that `resolv.conf` is generated by `NetworkManager` on a default (K)ubuntu system.

```
REMOTE_HOST_IP="172.17.0.1"
TLD_SUFFIX="local=$REMOTE_HOST_IP,test=$REMOTE_HOST_IP"
BIND_DNS_RESOLVER="192.168.10.9"
```

**Comment by pjdevries** [comment]
By the way, I gladly compensate some of your time for helping me. Maybe we can even use Signal to communicate more efficiently?

**Comment by degobbis** [comment]
You can find me on [Mattermost for Joomla](https://joom.la/chat) with the nick @guido-de-gobbis

**Comment by pjdevries** [comment]
See you there then :)
