### ISSUE TITLE
No problem with docker-lamp, 

### ISSUE THREAD

**Issue by astridx** [degobbis/docker-lamp#18]
but perhaps you have an idea?

https://github.com/mastodon/mastodon/discussions/22309

**Comment by degobbis** [comment]
Sorry, I'm in the final preparations for my vacation right now, which is why the Issue got lost.

Could the problem be solved and how?

**Comment by astridx** [comment]
No, I have not been able to solve it.
I wish you a nice vacation.

**Comment by astridx** [comment]
Just for your information. I have found a solution for myself. I have used [172.16.238.100](https://github.com/degobbis/docker-lamp/blob/4c5bc97b5f5fbd03eab1f56aee88c6c3fd61ee48/.config/httpd/apache24/config.yml#L19) as DNS on my computer. This way local applications and, websites in the docker environment, find each other. 

This way I only have extern connection (internet) when I start docker-lamp. 
Since it's a test system, that works for me.
