### ISSUE TITLE
Which branch do you ideally use at the moment when reinstalling docker-lamp? 

### ISSUE THREAD

**Issue by astridx** [degobbis/docker-lamp#6]
I just took the 2.0-dev branch. That has worked so far. Only the TLD are not recognized.
Am I doing something wrong or is this not ready yet?

```
$ bash docker-lamp start


Start creating SSL certificates:
Create certificate for: localdomains,localhost,joomla.local,joomla.test,*.joomla.local,*.joomla.test,wp.local,wp.test,*.wp.local,*.wp.test,wpms.local,wpms.test,*.wpms.local,*.wpms.test
docker: Error response from daemon: create ./data/ca: "./data/ca" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

All certificates created.
Start server:
[+] Running 12/12
 ⠿ Network docker-lamp_net           Created                                                                                   0.2s
 ⠿ Volume "docker-lamp_phpsocket"    Created                                                                                   0.0s
 ⠿ Volume "docker-lamp_db-data-dir"  Created                                                                                   0.0s
 ⠿ Volume "docker-lamp_pma"          Created                                                                                   0.0s
 ⠿ Container docker-lamp_bind        Started                                                                                   2.9s
 ⠿ Container docker-lamp_db          Started                                                                                   2.6s
 ⠿ Container docker-lamp_mailhog     Started                                                                                   3.1s
 ⠿ Container docker-lamp_phpmyadmin  Started                                                                                   4.6s
 ⠿ Container docker-lamp_php74       Started                                                                                   5.4s
 ⠿ Container docker-lamp_php80       Started                                                                                   5.3s
 ⠿ Container docker-lamp_php81       Started                                                                                   5.3s
 ⠿ Container docker-lamp_apache24    Started                                                                                   5.9s
Server started.
Restore databases:
MySQL init process in progress...
ignoring: README.md



$ make server-up
/home/astrid/docker-lamp/docker-lamp/.env included
[+] Running 8/8
 ⠿ Container docker-lamp_mailhog     Started                                                                                  13.5s
 ⠿ Container docker-lamp_bind        Started                                                                                  13.1s
 ⠿ Container docker-lamp_db          Started                                                                                  13.4s
 ⠿ Container docker-lamp_phpmyadmin  Started                                                                                   4.9s
 ⠿ Container docker-lamp_php74       Started                                                                                   5.1s
 ⠿ Container docker-lamp_php80       Started                                                                                   5.1s
 ⠿ Container docker-lamp_php81       Started                                                                                   5.1s
 ⠿ Container docker-lamp_apache24    Started                                                                                   5.0s

```

I am not yet looking for the certificate.

`http://localhost/joomla/` is fine.
`http://joomla.test/` / `http://joomla.local/` are redirectet to `https://www.joomla.test/` / `https://www.joomla.local/`. This URLs are not found.

My System is Ubuntu 20.4

**Comment by pe7er** [comment]
I use the **2.0.0-dev branch** on Ubuntu 20.04. I had some issues with creating SSL certificates for TLDs as well. One of my local site has 5 different domain names pointing to the same virtual host, and another (``test.local``) is just a separate local domain. 

@degobbis helpt me out:
- in my ``/docker-lamp/.env`` file I have configured my local SSL domains using:
  -  ``SSL_DOMAINS="de-beste-website.local,the-best-website.local,die-beste-website.local,le-meilleur-site-web.local,el-mejor-sitio-web.local test.local"`` (note: a comma between the 5 domains point to one virtual domain, and a space before the ``test.local``)
- in ``/srv/httpd/apache24/my-domains.conf`` I specified my own local domains like:
  - ``Use VHost de-beste-website.local "die-beste-website.local the-best-website.local el-mejor-sitio-web.local le-meilleur-site-web.local"``
  -  ``Use VHost test.local ""``
- I removed the certificate folders under ``/srv/ca/`` and restarted docker-lamp to recreate the right certificates

I hope this helps...

**Comment by degobbis** [comment]
Hi @pe7er,
in Your first `Use VHost` case, you have to create the folder like `/APP_BASEDIR/www/FIRST_DOMAIN_IN_USE_VHOST/` 
- `/APP_BASEDIR/www/de-beste-website.local/` an all other domains will automatically map to this (SSL-Cert too)

the second `Use VHost` is not really needed. You can add the SSL-Cert by adding the domain to `SSL_LOCALDOMAINS="test.local"` and only a directory `/APP_BASEDIR/www/test/` is needed. In this case, all subdomains will automatically map into the same named subfolders. 

If You intend to add aliases for this Domain, then Your described way is correct and the folder has to be the full domain like `test.local`. Subfolders do not map automatically in this way to subdomains.

**Comment by degobbis** [comment]
In the case of Astridx, it was several problems.

First, it was a misconfiguration of the network so that the bind container was not called to resolve domains.

Second, it could be a bug in my code that I can't reproduce at the moment. I need to check this out.
So `APP_BASEDIR `would not resolve correctly if the path is relative such as `./data`. However, it may also have been a permissions issue.
