### ISSUE TITLE
docker-lamp <command> --help

### ISSUE THREAD

**Issue by astridx** [degobbis/docker-lamp#7]
`docker-lamp <command> --help` does not work correctly on my computer.

```
$ ./docker-lamp shutdown --help
ERROR: The parameter --help is not set correctly!
For help call './docker-lamp --help'.

```

`docker-lamp --help` works fine.

```
$ ./docker-lamp --help
-- Help for the command: docker-lamp  --

Usage:
-> docker-lamp <command> [<parameters>]
...
```

![1](https://user-images.githubusercontent.com/9974686/171991321-e9a3d906-ac40-45ce-bc3e-4437707df5bf.PNG)

**Comment by degobbis** [comment]
Thx for reporting this, is now fixed.
