### ISSUE TITLE
Not all SSL certificates created 

### ISSUE THREAD

**Issue by pjdevries** [degobbis/docker-lamp#9]
I have the following settings in my `.env`:

```
EXTRA_HOSTS=info.obix.local=127.0.0.1,try.obix.local=127.0.0.1
SSL_DOMAINS=info.obix.local,try.obix.local
````

I have a `./data/httpd/apache24/00-extra-hosts.conf` with the following content:

```
Use VHost info.obix.local ""
Use VHost try.obix.local ""
```

When starting the container, it shows the following info:

```
Create certificate for: info.obix.local,try.obix.local
```

Unfortunately only the certificate for `info.obix.local` is created. The one for `try.obix.local` is not. Any idea what the reason might be?

**Comment by degobbis** [comment]
*SSL_DOMAINS="info.obix.local try.obix.local"

22.09.2022 15:45:22 Pieter-Jan de Vries ***@***.***>:

**Comment by pjdevries** [comment]
Enclosed in quotes and separated by space seems to do the trick indeed. A bit confusing, because of the different syntax for `EXTRA_HOSTS` :)

Equally slightly confusing is the comment in `.env-example`  on line 129 above `SSL_DOMAINS`:

```
# IMPORTANT: No spaces allowed!
#
SSL_DOMAINS=
SSL_LOCALDOMAINS=
```

In fact spaces are required as domain separators :)

Thanx again for your help.

**Comment by degobbis** [comment]
THX to bring my attention to this, I have to remove this.

**Comment by pjdevries** [comment]
You're welcome. 

Unfortunately I'm running into the next issue. Although certificates of both domains are now in place, the one for the second domain `try.obix.local` is not trusted and results in the dreaded **Warning: Potential Security Risk Ahead** message as a result of an `SSL_ERROR_BAD_CERT_DOMAIN` error.

EDIT: It appears the localdomains certificate is loaded.

Any suggestions?

**Comment by degobbis** [comment]
Please delete both dirs in `.data/ca` and restart the server. It will create it new.

**Comment by pjdevries** [comment]
I did. Even deleted all three. It does not solve the problem and it seems there's more than meets the eye. Trying to access the regular `http` version of `try.obix.local` even results in a 404. I've no idea whats wrong here, because both domains are setup exactly the same, as far as I can see. Unless I completely overlook something, which has proven to be somewhat of a weak spot of mine :(

I'll remove everything and start all over again to see what happens then.

**Comment by pjdevries** [comment]
I finally found the issue. As you can see in my first post, I had two `Use VHost ...` invocations in my `./data/httpd/apache24/00-extra-hosts.conf`. Apparently that's not allowed/possible. After creating separate `.conf` files with just one  `Use VHost ...` in each of them, all VHosts get served as expected.

**Comment by degobbis** [comment]
I have tested this several times now, and I could not reproduce your issue.

First, I shut down the server.

In my `.env` I added
```
EXTRA_HOSTS="info.obix.local=127.0.0.1,try.obix.local=127.0.0.1"
SSL_DOMAINS="info.obix.local try.obix.local"
```

In `./data/www` I created the two directories `info.obix.local` and `try.obix.local` and stored a TXT file with the domain name inside each.

In the `./data/httpd/apache24` I created the file `00-extra-hosts.conf` and added the two entries 
```
Use VHost info.obix.local ""
Use VHost try.obix.local ""
```
in it.

In `./data/ca` I deleted all subfolders but not the two `minica-root...pem` files.

I assume that, as described in my env-example, the mini-root-ca is stored in the browser :-)

Now I started the server, I could access both directories, with and without SSL.

Splitting the use commands into separate files is not necessary.

**Comment by pjdevries** [comment]
Thanx for the elaborate response. I'll check my setup more carefully and try it once more. Like I mentioned in the other issue, I must postpone that for a bit, because I must try to get some work done first. But I trust your findings, so let's consider this issue solved, until I run into similar problems.
